### ISSUE TITLE
Closing Client Connection Exception

### ISSUE THREAD

**Issue by TensorTom** [treeform/ws#1]
Running the server example, connecting with a websocket client then closing the client connection produced in the server: Error: unhandled exception: Socket got invalid frame, looking for Text or Binary [WebSocketError].

How to correct?

**Comment by treeform** [comment]
Hmm, I usually get `WebSocketError("socket closed")` as `Exception message: socket closed` it appears this happens when not a full frame is sent on closing.

Do you have an example that can replicate this?

**Comment by treeform** [comment]
Never mind I figured it out. I was not looking for the Close packet. Now I close the socket correctly.

https://github.com/treeform/ws/commit/391d129e009c38a19866147f4e7571e7f7010d1e
