### ISSUE TITLE
undeclared identifier: 'SslError'

### ISSUE THREAD

**Issue by narimiran** [treeform/ws#10]
This package is a part of `important_packages` which are continuously tested with every new commit to Nim's repository.

Since recently, it started to fail, with this error: `ws.nim(422, 10) Error: undeclared identifier: 'SslError'`.

I think this is something on your side (and not something that broke in the latest devel), and it might be connect to the [Better Exception Handling commit](https://github.com/treeform/ws/commit/658529cc0ae219baf9c611bbfd3c265559f66b03).

**Comment by zedeus** [comment]
`SslError` is only defined when compiled with `-d:ssl`, so this should either be wrapped in `when defined(ssl)` or something similar

**Comment by narimiran** [comment]
> `SslError` is only defined when compiled with `-d:ssl`, so this should either be wrapped in `when defined(ssl)` or something similar

What our tests do (in the case of this package) is `nimble test`. So I'm guessing some `nim.cfg` or `config.nims` is needed.

**Comment by zedeus** [comment]
Right, but you can't use the library at all without `-d:ssl` because of that one line.

**Comment by treeform** [comment]
Fixed. I'll just catch all exceptions and rewrap them.

https://github.com/treeform/ws/commit/085d4470b7fd88b980b86a8a548765353e0522bc
