### ISSUE TITLE
client.close() crashes server process

### ISSUE THREAD

**Issue by teroz** [treeform/ws#17]
I run the simple server code from README.md with a browser as the client. The  client is able to connect correctly but when the client code calls ws.close() the server crashes. Am running the latest version of the package 0.4.0 and nim 1.0.4 on Ubuntu. What's the issue?

**Comment by treeform** [comment]
What error do you get? You probably need to catch the websocket closed exception, see more advanced examples.

**Comment by teroz** [comment]
oic awesome thank you
