### ISSUE TITLE
Exception: "WebSocket potocol missmatch"

### ISSUE THREAD

**Issue by geohuz** [treeform/ws#19]
I'm facing a issue with using ws to receive stream data from a websocket server, the server is established with json-rpc over websocket and I have no control over it. The basic data receiving logic is to connect to server and send subscription msg on a channel, then start a loop to receive stream data from server,

```
# subscribe to channel 
  await ws.send("""
{
  "jsonrpc": "2.0",
  "method": "add",
  "params": {
    "data": ["notify"],
    "entity": "subscriptions",
    "userEmail": "xxxxx",
    "authToken": "xxxxx",
    "project_uid": "xxxxx"
  },
  "id": 2
}
""")

  echo await ws.receiveStrPacket()
  # start receiving stream data
  while ws.readyState == Open:
    let packet = await ws.receiveStrPacket()
    echo packet
   
ws.close()
....
```

the code running without issue and can receive data normally, but sometimes it throw exception: "Exception message: WebSocket Potocol missmatch
Exception type: [WebSocketError]", I'm wondering if there is any adjustment on my side can fix the issue?

**Comment by treeform** [comment]
When you connect a WebSocket client to a WebSocket server the protocol string needs to match on both ends. You can set protocol strings during WebSocket creation:

https://github.com/treeform/ws/blob/master/src/ws.nim#L111

Also see: 
https://tools.ietf.org/html/rfc6455#section-11.3.4

My personal option is that protocol matching is stupid and should not have been part of the spec.

**Comment by geohuz** [comment]
I've looked into my api document provided with server and I couldn't find the subprotocol string, and I've tried writing a similar program with python, it doesn't get any error. My scenario is, the nim version throws error during the same session, it ran very well at a moment, it seems that the exception happens when a change or update event sent from server.

**Comment by treeform** [comment]
Are you connecting to a public API I can test with?

You are saying you are getting a message with rsv1/2/3 set to true? If you comment that code out in the source does it work then?

**Comment by treeform** [comment]
If you provide a small example I could probably figure this out.

**Comment by mbuchel** [comment]
this error was very misleading, however this comes from compression not being implemented by treeform/ws.

https://tools.ietf.org/html/rfc7692

above is the rfc which makes sense of the first reserved bit which was being set to true. my guess is in this particular case the other person experienced the same bug.

**Comment by mbuchel** [comment]
oh nevermind my case it is different, it never works because the compression extension is not implemented yet

**Comment by mbuchel** [comment]
a work around which gets around my issue is to comment out this line:

https://github.com/treeform/ws/blob/e7708425a4a1fb10eac6d4420a86a9e6b12ed09c/src/ws.nim#L138

**Comment by treeform** [comment]
Thank for this. I have commented out the support for compression as well. Maybe one day I will add compression support then I'll add the header.

**Comment by mbuchel** [comment]
I am working on adding an extension on my fork of ws, i will push it here if i finish before you. Do you mind if we use python autobahn for testing that compression?

**Comment by treeform** [comment]
Sounds good. Not sure about python, would have to see it to know for sure. It would have to do compression and uncompressed easy to test with nim no?

**Comment by mbuchel** [comment]
it is easy to test with nim, i have unfortunately gotten a bit busy myself so have not been able to work more on the solution i am coming up with for this. the reason i decided to use python autobahn here is simply due to the fact that other web socket libraries use test benches made by them: https://github.com/crossbario/autobahn-testsuite

**Comment by treeform** [comment]
You right that test suit looks pretty cool. I am looking forward to seeing
anything that you produce.

**Comment by treeform** [comment]
@mbuchel Hey have you seen https://github.com/guzba/zippy ?

**Comment by mbuchel** [comment]
thank you for that, definitely will make my life easier, sorry it is taking so long i am caught up with my job's coding now

**Comment by geohuz** [comment]
> a work around which gets around my issue is to comment out this line:
> 
> https://github.com/treeform/ws/blob/e7708425a4a1fb10eac6d4420a86a9e6b12ed09c/src/ws.nim#L138

This fixed the problem and I have a websocket client running on the prodution now!

BTW, any suggestion on server close the socket? I found sometimes server close the socket but I want my client running without exception.
