### ISSUE TITLE
Can't connect to socket.io even after transformation

### ISSUE THREAD

**Issue by machineko** [treeform/ws#22]
So normally with other websockets libs (in js and python) I can just add ?EIO=3&transport=websocket on socket.io based endpoint and its working, but same cant be said about ws.
Am I missing something?

**Comment by treeform** [comment]
Never tested with socket.io. I used socket.io like 15 years ago... 

Do you have a simple example that shows the bug?

**Comment by machineko** [comment]
```nim
import asyncdispatch, strformat, net, strutils, ws

proc test_ws(w_t: string) {.async.} =
    echo("connecting")
    var web_s = await newWebSocket(&"wss://sockets.streamlabs.com/socket.io/?EIO=3&transport=websocket&token={w_t}")
    echo("connected")
    echo await web_s.receiveStrPacket()

let token = "smthtoken"
waitFor(test_ws(token))
```

https://streamlabs.com/dashboard#/settings/api-settings

Same request are working fine with nodejs websocket lib and in web without socket.io lib installed

**Comment by treeform** [comment]
I tried your example. I can't event connect to "sockets.streamlabs.com" it breaks on dial in the lower level stack.

https://github.com/nim-lang/Nim/blob/devel/lib/pure/httpclient.nim#L880

This is before it event sends SSL or HTTP headers. 

It feels like I am just blocked from connecting.

**Comment by treeform** [comment]
Oh, I think I have found a solution.

**Comment by treeform** [comment]
Ok fixed it here:
https://github.com/treeform/ws/commit/0379b236d1a1e9975da219013e44198f3c11811d

You should try the example.

**Comment by machineko** [comment]
Thanks ill try it tomorrow :)
