### ISSUE TITLE
Can't ping eninge io websocket 

### ISSUE THREAD

**Issue by machineko** [treeform/ws#24]
Based on https://github.com/socketio/engine.io-protocol/tree/v3 client need to ping server with message 2 to ping a server or connection will be closed. 
But when I'm trying to send message with value 2 using ws there is no response (again when using any chrome websockets plugins or js there is pong of value 3) So its probably msg formatting problem (?)
I was trying
```
wes.send("2")
wes.send("2", opcode=Opcode.Binary)
wes.send("2", opcode=Opcode.Ping)
```

Problem running on windows

**Comment by treeform** [comment]
Looking at the docs here: https://github.com/socketio/engine.io-protocol/tree/v3#encoding

It looks like it supports 2 versions string and binary, but string it looks like you need to send "2probe"

```nim
wes.send("2probe")
```

For binary it looks like it wants you to send a byte only, but you need to encode it as binary:
```
wes.send("\02", opcode=Opcode.Binary)
```

I don't recommend sending `Opcode.Ping` I don't think that is what you want.

**Comment by machineko** [comment]
Ye i was trying 2probe and stuff like this but it doesn't work.
Same about binary i've tried both hex and binary format (sorry for not sending it earlier didn't see I just change opcode in this test :P)
`wes.send("\02", opcode=Opcode.Binary)` 
Its something with message formatting but i cant find reason (I'm just learning nim and can't properly debug it yet)

**Comment by machineko** [comment]
https://chrome.google.com/webstore/detail/browser-websocket-client/mdmlhchldhfnfnkfmljgeinlffmdgkjo
server url = wss://sockets.streamlabs.com/socket.io/?EIO=3&transport=websocket&token=
message = 2
Is working fine 
I've also seen that most of the js socket lib and python websockets lib https://websockets.readthedocs.io/en/stable/intro.html 
are able to just send the data  without a problem

import asyncio
import websockets

```python
async def hello():
    uri = "wss://sockets.streamlabs.com/socket.io/?EIO=3&transport=websocket&token="
    async with websockets.connect(uri) as websocket:
        ping = "2"
        await websocket.send(ping)
        for i in range(2):
            greeting = await websocket.recv()
        for i in range(2):
            await websocket.send(ping)
            greeting = await websocket.recv()
            print(f"< {greeting}")

asyncio.get_event_loop().run_until_complete(hello())
```

**Comment by machineko** [comment]
Ok nothing was changed in my code and endpoint start working (?) (maybe endpoint update or i srsly dunno but ill close this issue)
