### ISSUE TITLE
Key not found: sec-websocket-protocol

### ISSUE THREAD

**Issue by icyphox** [treeform/ws#25]
I'm connecting to a remote websocket server, with the protocol `xmpp`. Here's what the proc definition looks like:
```nim
proc connectRemote(host: string) {.async.} =
  remote = await newWebSocket(host, protocol = "xmpp")
  let 
    hostPort = remote.tcpSocket.getPeerAddr()
    address = hostPort[0]
    port = hostPort[1].int
  echo fmt"connected to {address}:{port}"
```

And it errors while attempting to connect with
```
Exception message: key not found: sec-websocket-protocol
Exception type: [KeyError]
```

**Comment by treeform** [comment]
It seems like getPeerAdd does not work even when it connects. Its very strange I opened an issue with nim here: https://github.com/nim-lang/Nim/issues/15022

**Comment by icyphox** [comment]
Hmm getPeerAdd() is purely informational in my use-case anyway, so
that's not really a problem.
