### ISSUE TITLE
All exceptions are WebSocketError. More specific exceptions possible?

### ISSUE THREAD

**Issue by EriKWDev** [treeform/ws#28]
Hi!
I see that all exceptions being raised are just `WebSocketError`. It is hard to only except "Closed" exceptions in one way and other exceptions in their own ways.

Could we perhaps have something like `WebSocketClosedError`, `WebSocketProtocolMismatchError`, `WebSocketHandshakeError` and so on which could all be `object of WebSocketError`. This would ensure that scripts that already catch `WebSocketError` would still work (right?). 

I might take a look tonight and see if I can submit a PR

**Comment by EriKWDev** [comment]
I don't even know if `WebsocketClosedError` should be an error xP That one seems pretty integral for a websocket server that needs to keep track of connections.

Should it perhaps just be called `WebsocketClosed`? `WebsocketClosedExcpetion`? 
Doesn't really matter but hey, semantics in programming sure is fun...

**Comment by treeform** [comment]
Basically any exception from the websocket is a close. Would you handle WebSocketProtocolMismatchError, WebSocketHandshakeError differently? 

I think close should be an exception as the expected path for web socket to remain open forever.

**Comment by EriKWDev** [comment]
While I see what you mean, I also think that a specific Error as possible should be raised. I checked the test cases and a bunch of them except WebSocketError and assume that the thing that went wrong is in fact what the test is for, but with that mentality we might as well just raise Error since "it wouldn't be handled differently anyway" xP The test for protocol doesn't even except WebSocketError just 'except:'

If the new exceptions are all of 'object of WebSocketError', old try-excepts would still work like they already do and the tests could become more specific. It wouldn't cost anything but would allow for cleaner code. 

Some code duplication could go away as well since the WebSocketClosedError is raised in quite a few places. Perhaps a simple 'newWebSocketClosedError' with the correct message should be made?

**Comment by EriKWDev** [comment]
I also beleive that [this test (test_protocol_arr)](https://github.com/treeform/ws/blob/44fbe04a6f6bc4ec3d83782c1ec137f89906ffcf/tests/test_protocol_arr.nim#L42) is supposed to find a `WebSocketProtocolMismatchError`, but the actual `WebSocketError` being raised here is `Failed to Upgrade (Possibly Connected to non-WebSocket url` on my PC. Is this correct?

**Comment by treeform** [comment]
I would not mind WebSocketError hierarchy with WebsocketClosed, WebSocketProtocolMismatchError etc... I don't need it though, so I will not make this myself, but PRs welcome.

My fear is that we add this complexity but its not used by anyone in real production system and just creates a bigger bug surface.

**Comment by EriKWDev** [comment]
Well, I believe that having more specific errors does the opposite of creating a bigger bug surface since it allows for better tests and debugging.

Users can still just except WebSocketError if they don't care and catch them all.

I'll make a PR since I do want this for myself anyway :) 

Should the README be updated as well to contain the new Errors? Should the chatserv er example still use `except: WebSocketErrror`for the closing sockets or should it specifically except `WebSocketClosedError`?

**Comment by treeform** [comment]
Please update the examples. 

Don't worry about the README, we stopped using mddoc and use nimdocs now. I can change that part after your PR.

**Comment by treeform** [comment]
I updated the read me to our new style. Feel free to mess with it.
