### ISSUE TITLE
Custom error types throwing "undeclared identifier" error when running examples from fresh nimble install on v0.4.3

### ISSUE THREAD

**Issue by RattleyCooper** [treeform/ws#31]
Here is the code and the error message:

```nim
import asyncdispatch, asynchttpserver, ws

var connections = newSeq[WebSocket]()

proc cb(req: Request) {.async, gcsafe.} =
  if req.url.path == "/ws":
    try:
      var ws = await newWebSocket(req)
      connections.add ws
      await ws.send("Welcome to simple chat server")
      while ws.readyState == Open:
        let packet = await ws.receiveStrPacket()
        echo "Received packet: " & packet
        for other in connections:
          if other.readyState == Open:
            asyncCheck other.send(packet)
    except WebSocketClosedError:
      echo "Socket closed. "
    except WebSocketProtocolMismatchError:
      echo "Socket tried to use an unknown protocol: ", getCurrentExceptionMsg()
    except WebSocketError:
      echo "Unexpected socket error: ", getCurrentExceptionMsg()
  await req.respond(Http200, "Hello World")

var server = newAsyncHttpServer()
waitFor server.serve(Port(9001), cb)
```

`serve.nim(5, 25) template/generic instantiation of  'async' from here`

`serve.nim(17, 12) Error: undeclared identifier: 'WebSocketClosedError'`

I thought that maybe the `var ws = await newWebSocket(req)` line might be causing issues since the package is named `ws` but changing the variable name produces the same results.

**Comment by RattleyCooper** [comment]
@treeform The issue is the v0.4.3 release does not include the type definitions for the additional errors in `ws.nim`.

**Comment by treeform** [comment]
The code above works for me. I think the issues is that I just need to tag another version. I have tagged version 0.4.4 please let me know if installing this new version solves your issue?

**Comment by RattleyCooper** [comment]
Yeah, sounds correct.  Tested it and it's working 🥳
