### ISSUE TITLE
Typo in README (complaint -> compliant)?

### ISSUE THREAD

**Issue by evertrol** [treeform/ws#34]
The README reads, under "Features:"

> - Complaint: https://tools.ietf.org/html/rfc6455

I assume this is a typo, and "compliant" is meant. Usually, a typo is easy to correct, but there, it changes the implied meaning drastically: either `ws` disagrees with the websocket protocol implementation ("complaint"), or it agrees with the protocol ("compliant").

-----

Aside, I also think it should read:

- compliant with the [WebSocket protocol](https://tools.ietf.org/html/rfc6455)

which is more of a normal sentence, and makes it immediately clear what the link is about.

**Comment by treeform** [comment]
Thanks! Fixed: https://github.com/treeform/ws/commit/0e197f2edfbc8558e3af202ee1118cd0b90010e2
