### ISSUE TITLE
ws with JS backend?

### ISSUE THREAD

**Issue by matkuki** [treeform/ws#36]
Hi,

How do I compile the client example from the readme for Javascript:
```nim
var ws = await newWebSocket("ws://127.0.0.1:9001/ws")
echo await ws.receiveStrPacket()
await ws.send("Hi, how are you?")
echo await ws.receiveStrPacket()
ws.close()
```
?

Thanks

**Comment by treeform** [comment]
Sorry `ws` does not support Javascript. The "client" here refers to "WebSocket Client" not "Browser Client".

You can use some thing like this use the JS WebSocket API: https://github.com/stisa/jswebsockets

I hope that helps!

**Comment by matkuki** [comment]
Excellent, thanks 👍
