### ISSUE TITLE
Test example fails

### ISSUE THREAD

**Issue by MachineTrader** [treeform/ws#38]
I'm trying to write a short test example. But it fails.

`
import ws, asyncdispatch

let baseurl = "wss://stream.binance.com:9443/ws/"
let stream = "btcusdt@bookTicker"
let payload = baseurl & stream

var wsoc = await newWebSocket(payload)
echo await wsoc.receiveStrPacket()
wsoc.close()
`

The error message I receive is :

App.nim(7, 18) template/generic instantiation of `await` from here
C:\Dev\nim-1.6.4_x64\nim-1.6.4\lib\pure\asyncmacro.nim(130, 3) Error: 'yield' only allowed in an iterator

**Comment by treeform** [comment]
Sorry the README makes it not clear thats is just a snippet. Nim's await system requires some setup. I have updated the example to include the setup as well.

I hope its more clear!

**Comment by treeform** [comment]
Here is an example file: https://github.com/treeform/ws/blob/master/tests/sender.nim
