### ISSUE TITLE
server can't keep websocket connection alive and won't send any data

### ISSUE THREAD

**Issue by d4rckh** [treeform/ws#39]
I am struggling on this for more than a day and I can not figure out what's wrong.

My program runs multiple async proc's including a jester server with a ws endpoint;

```nim
  get "/ws":
    var ws = await newWebSocket(request)
    {.cast(gcsafe).}:
      connections.add ws
    while ws.readyState == Open:
      let packet = await ws.receiveStrPacket()
      echo packet
    resp "ok"
```

`connections` is a global sequence: 
```nim
var connections = newSeq[WebSocket]()
```

I also have this proc that gets called from an async proc sometimes:

```nim
proc notifyClientConnection*(client: Client) {.async.} =
  for connection in connections:
    if connection.readyState == Open:
      await connection.send($client.id)
```

The problem is that nothing is being sent, despite the connection being open. Another issue is that the connection gets closed (after I try to send something for the first time in the session) without the client being notified that the connection got closed. I have no idea what's happening. There are no errors thrown on the client or the server. I think it must be a problem with the library?

Edit: I added another call to connection.send before the first one and now they both work. I restarted the websocket server and they both stopped worked. Added a third send call and they all started working again, of course until I restarted the server, it wont work until I edit that specific function and recompile the code.

**Comment by treeform** [comment]
I basically do the same thing, and it's been working for me for years.

Could you make a simple-stupid runnable example?
I don't use Jester, maybe it's that?
Maybe jester wants the request to return quickly and while look makes it block?
Maybe the way you call notifyClientConnection is not right?
Are you using threaded Jester? Each thread is isolated from each other so they will get different `connections`.
Are you on Window or Mac? I mainly run servers on linux.

I hope that helps.

**Comment by d4rckh** [comment]
> I basically do the same thing, and it's been working for me for years.
> 
> Could you make a simple-stupid runnable example? I don't use Jester, maybe it's that? Maybe jester wants the request to return quickly and while look makes it block? Maybe the way you call notifyClientConnection is not right? Are you using threaded Jester? Each thread is isolated from each other so they will get different `connections`. Are you on Window or Mac? I mainly run servers on linux.
> 
> I hope that helps.

Thanks for replying!

I tried putting the connections in a sequence that's an attribute of a ref object but that still didn't fix the issue. Jester is running asynchronously. Also, I get the correct amount of connections every time I print `len connections`

**Comment by treeform** [comment]
A simple example that shows the issue could be great.

**Comment by d4rckh** [comment]
I tried to isolate the code of the ws client and ws server in a new project and it's working fine.... I really can't figure out what's the problem. I put the code in this repo: https://github.com/d4rckh/nimws-test. To use this, install `ws` & `jester` and then
1. Run `nim r main.nim` -> start a tcp server and a ws server
2. open `wsClient.html` in your browser
3. Run `nim r tcpClient.nim`
- The ws server should notify the ws client that somebody connected to the tcp server

Again, this code works fine, but it's not working in my project, even if it's really almost the same thing with some added functionality.

**Comment by treeform** [comment]
I think the problem is added functionality, keep adding things till you find it?

**Comment by d4rckh** [comment]
> I think the problem is added functionality, keep adding things till you find it?

Well, the added functionality is just the parsing of the messages received by the TCP server. It's actually pretty hard to debug since there are no thrown errors. Is there any way I could find the reason the socket randomly closes on the server?

**Comment by d4rckh** [comment]
Ok, I actually found this error being thrown every few minutes while I was debugging and the client connected to the ws server.

```
ERROR /home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(371) eventLoop
/home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(227) processEvents
/usr/lib/nim/pure/asyncdispatch.nim(1653) poll
/usr/lib/nim/pure/asyncdispatch.nim(1394) runOnce
/usr/lib/nim/pure/asyncdispatch.nim(234) processPendingCallbacks
/usr/lib/nim/pure/asyncmacro.nim(28) receiveStrPacketNimAsyncContinue
/home/andrei/.nimble/pkgs/ws-0.5.0/ws.nim(434) receiveStrPacketIter
[[reraised from:
/home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(371) eventLoop
/home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(227) processEvents
/usr/lib/nim/pure/asyncdispatch.nim(1653) poll
/usr/lib/nim/pure/asyncdispatch.nim(1394) runOnce
/usr/lib/nim/pure/asyncdispatch.nim(234) processPendingCallbacks
/usr/lib/nim/pure/asyncmacro.nim(28) myrouterNimAsyncContinue
/usr/lib/nim/pure/asyncmacro.nim(131) myrouterIter
/usr/lib/nim/pure/asyncfutures.nim(389) read
]]
[[reraised from:
/home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(371) eventLoop
/home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(227) processEvents
/usr/lib/nim/pure/asyncdispatch.nim(1653) poll
/usr/lib/nim/pure/asyncdispatch.nim(1394) runOnce
/usr/lib/nim/pure/asyncdispatch.nim(234) processPendingCallbacks
/usr/lib/nim/pure/asyncmacro.nim(28) dispatchNimAsyncContinue
/usr/lib/nim/pure/asyncmacro.nim(131) dispatchIter
/usr/lib/nim/pure/asyncfutures.nim(389) read
]]
[[reraised from:
/home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(371) eventLoop
/home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(227) processEvents
/usr/lib/nim/pure/asyncdispatch.nim(1653) poll
/usr/lib/nim/pure/asyncdispatch.nim(1394) runOnce
/usr/lib/nim/pure/asyncdispatch.nim(234) processPendingCallbacks
/usr/lib/nim/pure/asyncmacro.nim(28) handleRequestSlowNimAsyncContinue
/usr/lib/nim/pure/asyncmacro.nim(131) handleRequestSlowIter
/usr/lib/nim/pure/asyncfutures.nim(389) read
]]
Socket closed
Async traceback:
  /home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(371) eventLoop
  /home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(227) processEvents
  /usr/lib/nim/pure/asyncdispatch.nim(1653)                    poll
  /usr/lib/nim/pure/asyncdispatch.nim(1394)                    runOnce
  /usr/lib/nim/pure/asyncdispatch.nim(234)                     processPendingCallbacks
  /usr/lib/nim/pure/asyncmacro.nim(28)                         receiveStrPacketNimAsyncContinue
  /home/andrei/.nimble/pkgs/ws-0.5.0/ws.nim(434)               receiveStrPacketIter
  #[
    /home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(371) eventLoop
    /home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(227) processEvents
    /usr/lib/nim/pure/asyncdispatch.nim(1653)                    poll
    /usr/lib/nim/pure/asyncdispatch.nim(1394)                    runOnce
    /usr/lib/nim/pure/asyncdispatch.nim(234)                     processPendingCallbacks
    /usr/lib/nim/pure/asyncmacro.nim(28)                         myrouterNimAsyncContinue
    /usr/lib/nim/pure/asyncmacro.nim(131)                        myrouterIter
    /usr/lib/nim/pure/asyncfutures.nim(389)                      read
  ]#
  #[
    /home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(371) eventLoop
    /home/andrei/.nimble/pkgs/httpbeast-0.4.0/httpbeast.nim(227) processEvents
    /usr/lib/nim/pure/asyncdispatch.nim(1653)                    poll
    /usr/lib/nim/pure/asyncdispatch.nim(1394)                    runOnce
    /usr/lib/nim/pure/asyncdispatch.nim(234)                     processPendingCallbacks
    /usr/lib/nim/pure/asyncmacro.nim(28)                         dispatchNimAsyncContinue
    /usr/lib/nim/pure/asyncmacro.nim(131)                        dispatchIter
    /usr/lib/nim/pure/asyncfutures.nim(389)                      read
  ]#
Exception message: Socket closed

DEBUG   502 Bad Gateway {"content-type": @["text/html;charset=utf-8"]}
```

The ws code is identical to the one from the repo I linked above.

**Comment by treeform** [comment]
Do you send like a heart beat every 30-60s? In a real time game or some thing there is usually a simulation turn that acts as the heart beat. Some times OS will timeout your socket if you did not send anything in while. You can setup client's WebSocket regular pings with `setupPings` - a lot of times its not necessary and eats up bandwidth. I don't know if this is your issue.

I usually run "pure websocket" servers without jester/httpbeast. They only do websockets. Maybe keep your jester/httpbeast stack separate?

**Comment by d4rckh** [comment]
> Do you send like a heart beat every 30-60s? In a real time game or some thing there is usually a simulation turn that acts as the heart beat. Some times OS will timeout your socket if you did not send anything in while. You can setup client's WebSocket regular pings with `setupPings` - a lot of times its not necessary and eats up bandwidth. I don't know if this is your issue.
> 
> I usually run "pure websocket" servers without jester/httpbeast. They only do websockets. Maybe keep your jester/httpbeast stack separate?

I don't send any heart beat. I think running it separately would be a better idea. Can I run ws asynchronously along with other things?

**Comment by treeform** [comment]
That's how I run it for the most part.

**Comment by d4rckh** [comment]
I think I might have fixed it by using asynchttpserver instead of jester!!

**Comment by treeform** [comment]
You can see how jester integration is done: https://github.com/treeform/ws/blob/master/src/ws/jester_extra.nim

Maybe some thing can be fixed there?

**Comment by d4rckh** [comment]
I don't really know

**Comment by MrNavaStar** [comment]
I think this must be an issue with your client, as I have an almost identical setup in jester and it is working. However when the client disconnects the same error from above is thrown. It would be nice if there was a more elegant way to handle the disconnect, rather than a try except, but its alright.

In the meantime, I might update the readme to look something like this? Just to be a bit more beginner friendly.
```nim
routes:
  get "/ws":
    try:
      var ws = await newWebSocket(request)
      await ws.send("Welcome to simple echo server")
      while ws.readyState == Open:
        let packet = await ws.receiveStrPacket()
        await ws.send(packet)

    except WebSocketClosedError:
      echo("connection was closed")

    resp ""
```
Also note that without the `resp` at the end, jester throws some errors.
