### ISSUE TITLE
pingLoop causes SEGVs

### ISSUE THREAD

**Issue by srozb** [treeform/ws#41]
Hi,
I was trying to write code that will reconnect the websocket connection once it's broken for any reason, like this:

```nim
var csSock: WebSocket  # defined in some scope

proc setup(csSock: var WebSocket) =
  csSock = waitFor newWebSocket(CSURL)
  csSock.setupPings(15)

proc getMsg(csSock: var WebSocket): string = 
  try:
      result = waitFor csSock.receiveStrPacket
    except WebSocketError:
      csSock.setup

while true:
  discard getMsg()
```

I believe `setupPings(15)` proc will create a new async task that will periodically send pings to a given WebSocket. In case socket disconnection and a new socket created, the application will terminate with very unclear segmentation fault (attempt to read from nil). Perhaps the ping task is trying to access the memory address that was previously assigned to the old socket? Not sure, anyway commenting out the setupPings line solves this issue.

I'm not sure if this is a library fault or just me using this library in a wrong way but I'll be happy to provide more evidence on this behavior if needed.

**Comment by treeform** [comment]
This is a hard one. After spending an hour to debug this I think its a bug or incorrect usage of async.

Your example is not a full example, so I created my own:

## disconnector.nim

```nim
import asyncdispatch, asynchttpserver, ws

proc cb(req: Request) {.async.} =
  try:
    var ws = await newWebSocket(req)
    await ws.send("Welcome to disconnection server")
    for i in 0 ..< 5:
      await ws.send("disconnecting in " & $(5 - i))
      await sleepAsync(1000)
    ws.close()

  except WebSocketClosedError:
    echo "socket closed:", getCurrentExceptionMsg()

var server = newAsyncHttpServer()
waitFor server.serve(Port(9001), cb)
```

and

## reconnector.nim
```nim
import ws, asyncdispatch, strutils

var socket: WebSocket

proc newConnection() =
  echo "Connecting..."
  socket = waitFor newWebSocket("ws://localhost:9001")
  socket.setupPings(15)

proc getMessage() {.async.} =
  try:
    echo "Got message: ", await socket.receiveStrPacket()
  except WebSocketError:
    echo "WebSocketError!"
    newConnection()

newConnection()
while true:
  waitFor getMessage()
```

All work no problem... 

but if I use `waitFor` internally in getMessage() like you do it SEGFAULTS some where in the async TCP stack.

## broken_reconnector.nim
```nim
import ws, asyncdispatch, strutils

var socket: WebSocket

proc newConnection() =
  echo "Connecting..."
  socket = waitFor newWebSocket("ws://localhost:9001")
  socket.setupPings(15)

proc getMessage() =
  try:
    echo "Got message: ", waitFor socket.receiveStrPacket()
  except WebSocketError:
    echo "WebSocketError!"
    newConnection()

newConnection()
while true:
  getMessage()
```

I don't know how to fix this, its some sort of waitFor/await issue. They should be nearly identical but they are not.

Its probably best to only have a single waitFor in your program to start the async system and only use await from then on.

What do you think?

**Comment by srozb** [comment]
First of all I'm sorry for not providing minimal working example to aid your investigation. 

I was also suspecting either a bug in waitFor/await or me using those constructs in incorrect way. The real issue is that [waitFor documetation](https://nim-lang.org/docs/asyncdispatch.html#waitFor%2CFuture%5BT%5D) is very brief and the segmentation fault looks very misleading in my case:

```
/Users/slawek/.nimble/pkgs/cligen-1.5.24/cligen.nim(793) certstream
/Users/slawek/.nimble/pkgs/cligen-1.5.24/cligen.nim(722) multiSubs
/Users/slawek/.nimble/pkgs/cligen-1.5.24/cligen.nim(793) multi
/Users/slawek/.nimble/pkgs/cligen-1.5.24/cligen.nim(722) dispatchhunt
/Users/slawek/src/nim/certstream/src/certstream.nim(41) hunt
/Users/slawek/src/nim/certstream/src/certstream.nim(23) getMsg
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
[1]    73003 segmentation fault  ./certstream
```
How I understand this traceback is 23rd line of `certstream.nim` which basically is `result = waitFor csSock.receiveStrPacket` is attempting to read from nil which is absolutely not true because adding a line `echo waitFor csSock.receiveStrPacket` before, shows me real content of websocket message.

I spent whole day yesterday to debug it and it took me while to find that removing `setupPings` prevents those segmentation faults.

Moreover, as I don't use unmanaged and unsafe things like `unsafeAddr` or `cast` I don't really expect my code to cause segmentation faults.

This led me to create an issue, so the others won't waste more hours on debugging this weirdness. I guess all you can do is to close it or perhaps enrich your documentation somehow.
