### ISSUE TITLE
Sending custom headers when opening a client connection

### ISSUE THREAD

**Issue by Yepoleb** [treeform/ws#45]
Hello,

I would have liked to send an authorization header when establishing a client connection but found no way to do so. I worked around this by making the authorization token a URL parameter, but it would have been nicer if it was a header. Maybe this can be included in a future API change.

**Comment by treeform** [comment]
Its not part of the WebSocket spec. See more here: https://github.com/treeform/ws/pull/35

**Comment by Yepoleb** [comment]
Alright, thanks for your response!
