### ISSUE TITLE
gcsafe error

### ISSUE THREAD

**Issue by mmmmcoffee** [treeform/ws#48]
Running example echo or chat server gives compiler error:

asyncmacro.nim(250,31) error: "cb (Async)' is not GC-safe as it accesses 'connections' which is a global GC'ed memory

**Comment by danbarbarito** [comment]
I ran into this issue as well. I fixed it by doing this...

```nim
import ws, asyncdispatch, asynchttpserver

var connections {.threadvar.}: seq[WebSocket]

proc initThread() =
  connections = newSeq[WebSocket]()

proc cb(req: Request) {.async, gcsafe.} =
  if req.url.path == "/ws":
    try:
      var ws = await newWebSocket(req)
      connections.add ws
      await ws.send("Welcome")
      while ws.readyState == Open:
        let packet = await ws.receiveStrPacket()
        for other in connections:
          if other.readyState == Open:
            asyncCheck other.send(packet & " from the server")
    except WebSocketError:
      echo "socket closed:", getCurrentExceptionMsg()
  else:
    await req.respond(Http404, "Not found")


initThread()
var server = newAsyncHttpServer()
waitFor server.serve(Port(9001), cb)

```

**Comment by treeform** [comment]
Sorry `async` is very hard to make thread safe, therefore I can't commit to making `ws` thread safe as it depends on `async`.

If you want to go thread route, you should use the blocking TCP. For that try: https://github.com/guzba/whisky (which is slightly based on this repo)

I don't want to add an example that would mislead people combining async+threads in `ws`.

I am moving a way from `async` into threads using https://github.com/guzba/mummy and https://github.com/guzba/whisky for websocket work.

I hope this helps!
