### ISSUE TITLE
Alternate Opcodes?

### ISSUE THREAD

**Issue by idiot-with-a-keyboard** [treeform/ws#49]
Im probably being stupid here but how do i use alternate opcodes?
Im trying to send an opcode of 2 and ill need to send one of 13 later but its not allowing me to
Is it possible to make the function accept an integer for opcodes?

**Comment by treeform** [comment]
There is no opcode 13: https://datatracker.ietf.org/doc/html/rfc6455#section-11.8

Opcode of 2 means you want to send binary data? You can send that as second parameter to send: https://github.com/treeform/ws/blob/master/src/ws.nim#L292

Both text and binary are the same thing and there is no byte difference, only the opcode changes.
