### ISSUE TITLE
Protocol for client

### ISSUE THREAD

**Issue by dom96** [treeform/ws#5]
When using ``newWebSocket`` how are we meant to specify the protocol?

Here is a quick diff I cooked up to do it:

```nim
diff --git a/src/ws.nim b/src/ws.nim
index 83c04aa..77e4f8e 100644
--- a/src/ws.nim
+++ b/src/ws.nim
@@ -86,11 +86,12 @@ proc newWebSocket*(req: Request): Future[WebSocket] {.async.} =
   return ws
 
 
-proc newWebSocket*(url: string): Future[WebSocket] {.async.} =
+proc newWebSocket*(url: string, protocol = ""): Future[WebSocket] {.async.} =
   ## Creates a client
   var ws = WebSocket()
   ws.req = Request()
   ws.req.client = newAsyncSocket()
+  ws.protocol = protocol
 
   var uri = parseUri(url)
   var port = Port(9001)
@@ -114,6 +115,8 @@ proc newWebSocket*(url: string): Future[WebSocket] {.async.} =
     "Sec-WebSocket-Key": "JCSoP2Cyk0cHZkKAit5DjA==",
     "Sec-WebSocket-Extensions": "permessage-deflate; client_max_window_bits"
   })
+  if ws.protocol.len != 0:
+    client.headers["Sec-WebSocket-Protocol"] = ws.protocol
   var _ = await client.get(url)
   ws.req.client = client.getSocket()
 
```

Personally I would change this API:

* ``newWebSocket`` should **only** initialise the object, it shouldn't perform any connections
* a ``connect`` proc

Also I ran into other issues:

* No PING/PONG handling in the client?

**Comment by treeform** [comment]
So I added a way to specify protocol. https://github.com/treeform/ws/commit/6fa772c72d724d2d1564c9f72938a505f123a261

Why do you think I should split up the newWebSocket/connect. I like that I can create newWebSocket from a request for server side or from a url for client side. If I switch it client side I would switch to to newWebSocket/connect(request) as well? Is there a need in creation WebSockets but not using them? Maybe you are pooling them?

I still need to do the ping/pong.

**Comment by treeform** [comment]
I added basic support for pings here: https://github.com/treeform/ws/commit/eb3348932c4c20c31cdc700210b75967d8890101
